[theme]
primaryColor = "#38bdf8"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f8fafc"
base = "dark"

[client]
toolbarMode = "viewer"
showSidebarNavigation = true

[browser]
gatherUsageStats = false
